---
# filename: roles/openldap-auth-client/tasks/configure.yml
# run authconfig instead of manually editing files
- name: copy sssd file
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    force: false
    backup: true
    mode: 0600
  notify:
    - run authconfig
    - restart caching service
