---
# filename: roles/openldap-auth-client/tasks/install.yml
- name: install openldap client
  apt:
    name: "{{ openldap['pkgs'] }}"
    update_cache: "{{ update_cache }}"
    cache_valid_time: 3600
  notify:
    - restart nscd service
    - update pam auth

- name: activate libnss-lab module
  shell: sysv-rc-conf libnss-ldap on
  notify:
    - restart nscd service
    - update pam auth
